[manager]
ratio          = [ 0, 5, 3 ]
sort_by        = "alphabetical"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
zathura = [
    { run = 'zathura "$@"', orphan = true, for = "unix" },
]

[open]
prepend_rules = [
    { name = "*.cbz", use = "zathura" },
    { name = "*.pdf", use = "zathura" },
    { name = "*.epub", use = "zathura" },
]
